[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@pendle/=lib/pendle-core-v2-public"
]

ignored_warnings_from = ["test", "lib"]

optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[fuzz]
runs = 1

[invariant]
runs = 1
depth = 100
show_metrics = true
fail_on_revert = true